version: '3'
services:
  cobot-ros2:
    image: cobot-docker:latest 
    build:
      context: .
      dockerfile: ./Dockerfile
    security_opt:
     - apparmor:unconfined
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     # - ./moveit_task_constructor:/colcon_ws/src/moveit_task_constructor
     # - ./mycobot_ros2:/colcon_ws/src/mycobot_ros2
    environment:
      DISPLAY: $DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      ROS_MASTER_URI: https://192.168.0.222:11311
      ROS_IP: 192.168.0.222
      PYTHONPATH: ./
    working_dir: /colcon_ws
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
   
    #command: nvidia-smi -l
    command: ros2 launch mycobot_600 test.launch.py

    
